logging.level:
  root: info
  org.hibernate.SQL: debug
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

path:
  upload: "/images"
  resource: "file:///images/mabcci/images/local"
  real: "Users/mabcci/images/local"

