logging.level:
  root: info
  org.hibernate.SQL: debug
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  redis:
    port: 6387
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
path:
  upload: "/images"
  resource: "file:///mabcci/images/prod"
  real: "mabcci/images/prod"

